#!/bin/bash
if [ $# -ne 1 ] ; then
    echo "Usage: ./publish_homepage --page | --pubs | --pic | --sensiso"
    exit
fi

if [ $1 = "--page" ] ; then
    rsync -rz --progress ./*.php melara@tux.cs.princeton.edu:~/../htdocs/melara/
    rsync -rz --progress ./style.css melara@tux.cs.princeton.edu:~/../htdocs/melara/
elif [ $1 = "--pubs" ] ; then
    rsync -rz --progress ./pubs/*.pdf melara@tux.cs.princeton.edu:~/../htdocs/melara/pubs/
elif [ $1 = "--pic" ] ; then
    rsync -rz --progress ./marci.jpg melara@tux.cs.princeton.edu:~/../htdocs/melara/
elif [ $1 = "--sensiso" ] ; then
    rsync -rz --progress ./sensor_isolation/* melara@tux.cs.princeton.edu:~/../htdocs/melara/sensor_isolation/
    rsync -rz --progress ./sensor_isolation/.htaccess melara@tux.cs.princeton.edu:~/../htdocs/melara/sensor_isolation/
fi
    
