name: publish-site
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repo
              uses: actions/checkout@v2

            - name: set up permissions
              run chmod 755 ./publish.sh