#!/bin/bash
if [ $1 = "--all" ] ; then
    scp ./*.php melara@tux.cs.princeton.edu:~/../htdocs/melara/
    scp ./style.css melara@tux.cs.princeton.edu:~/../htdocs/melara/
    scp ./pubs/*.pdf melara@tux.cs.princeton.edu:~/../htdocs/melara/
    scp ./multisurf/* melara@tux.cs.princeton.edu:~/../htdocs/melara/multisurf/
    scp ./marci.jpg melara@tux.cs.princeton.edu:~/../htdocs/melara/
elif [ $1 = "--page" ] ; then
    scp ./*.php melara@tux.cs.princeton.edu:~/../htdocs/melara/
    scp ./style.css melara@tux.cs.princeton.edu:~/../htdocs/melara/
elif [ $1 = "--pubs" ] ; then
    scp ./pubs/*.pdf melara@tux.cs.princeton.edu:~/../htdocs/melara/pubs/
elif [ $1 = "--pic" ] ; then
    scp ./marci.jpg melara@tux.cs.princeton.edu:~/../htdocs/melara/
elif [ $1 = "--multisurf" ] ; then
    scp ./multisurf/* melara@tux.cs.princeton.edu:~/../htdocs/melara/multisurf/
elif [ $1 = "--vm" ] ; then
    scp ./second.ova melara@tux.cs.princeton.edu:~/../htdocs/melara/
fi
    
